version: '3.3'

services:
  client:
    container_name: client
    image: com402/hw4ex2_client
    privileged: true
  mitm:
    container_name: mitm
    image: mitm
    image: com402/hw4ex2_mitm
    privileged: true
    volumes:
      - '.:/app'